name: "beefy_databarn"
version: "1.0.0"
config-version: 2

profile: "beefy_databarn"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  beefy_databarn:
    staging:
      +schema: "{{ env_var('DBT_CLICKHOUSE_STAGING_DB', 'dbt') }}"
      +tags: ["staging"]
    intermediate:
      +schema: "{{ env_var('DBT_CLICKHOUSE_STAGING_DB', 'dbt') }}"
      +tags: ["intermediate"]
    dimensions:
      +schema: "{{ env_var('DBT_CLICKHOUSE_DB', 'analytics') }}"
      +tags: ["dimensions"]
      +materialized: table
    marts:
      +schema: "{{ env_var('DBT_CLICKHOUSE_DB', 'analytics') }}"
      +tags: ["marts"]

data_tests:
  +severity: error # all tests default to error
