version: 2

models:
  - name: product
    description: "Dimension table for product (vault) reference data. Provides product/vault metadata for joining with fact tables."
    config:
      contract:
        enforced: true
      meta:
        primary_key: ["chain_id", "product_address"]
    columns:
      - name: chain_id
        description: "Chain ID where the product exists"
        data_type: Int64
        tests:
          - not_null
      - name: product_type
        description: "Type of product (classic_vault, clm_manager, classic_boost, or reward_pool)"
        data_type: String
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['classic_vault', 'clm_manager', 'classic_boost', 'reward_pool']
      - name: product_address
        description: "Product contract address"
        data_type: String
        tests:
          - not_null
      - name: beefy_key
        description: "Beefy-specific vault/product identifier"
        data_type: String
        tests:
          - not_null
      - name: display_name
        description: "Product/vault display name"
        data_type: String
        tests:
          - not_null
      - name: is_active
        description: "Whether the vault is currently active"
        data_type: Bool
        tests:
          - not_null
      - name: platform_id
        description: "Platform identifier"
        data_type: Nullable(String)
        tests:
          - relationships:
              arguments:
                to: ref('platform')
                field: platform_id
      - name: creation_block
        description: "Block number when the product was initialized (from envio)"
        data_type: Nullable(Int64)
        tests:
          - dbt_utils.expression_is_true:
              arguments:
                expression: "is null or creation_block != 0"
      - name: creation_datetime
        description: "Timestamp when the product was initialized (from envio)"
        data_type: Nullable(DateTime64(3, 'UTC'))
        tests:
          - dbt_utils.expression_is_true:
              arguments:
                expression: "is null or creation_datetime >= '2020-01-01'"
