version: 2

models:
  - name: int_revenue_daily
    description: "Intermediate model transforming BIFI buyback events into revenue structure. Maps buyback_total to revenue_amount for revenue analysis."
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - id
              - event_timestamp
    columns:
      - name: id
        tests:
          - not_null
      - name: revenue_amount
        description: "Revenue amount (buyback_total from source)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: true
      - name: currency
        description: "Currency code (BIFI)"
        tests:
          - not_null
      - name: event_date
        tests:
          - not_null
      - name: bifi_amount
        description: "Amount of BIFI tokens"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: true
      - name: bifi_price
        description: "Price of BIFI at buyback time"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: true
