{{
  config(
    materialized='table',
    pre_hook=[
      "DROP TABLE IF EXISTS {{ this }}",
      "CREATE OR REPLACE TABLE {{ this }} (
        id Int32,
        block_number Int32,
        txn_timestamp DateTime64(6, 'UTC'),
        event_idx Nullable(Int16),
        txn_hash String,
        bifi_amount Decimal(26, 18),
        bifi_price Decimal(26, 18),
        buyback_total Nullable(Decimal(26, 18))
      ) ENGINE = PostgreSQL('{{ var(\"beefy_db_host\") }}:{{ var(\"beefy_db_port\") }}', '{{ var(\"beefy_db_name\") }}', 'bifi_buyback', '{{ var(\"beefy_db_user\") }}', '{{ var(\"beefy_db_password\") }}')"
    ]
  )
}}

-- Staging model: External table pointing to beefy-db PostgreSQL database
-- This creates a ClickHouse external table using the PostgreSQL engine
-- to federate queries to the source database
-- The table engine configuration creates a live connection to PostgreSQL
-- Note: The pre-hook creates the table with PostgreSQL engine, and this SELECT is a no-op
/**
                                                Table "public.bifi_buyback"
   Column     |           Type           | Collation | Nullable |                         Default                         
---------------+--------------------------+-----------+----------+---------------------------------------------------------
| id            | integer                  |           | not null | generated by default as identity
| block_number  | integer                  |           | not null | 
| txn_timestamp | timestamp with time zone |           | not null | 
| event_idx     | smallint                 |           |          | 
| txn_hash      | character(66)            |           | not null | 
| bifi_amount   | numeric(26,18)           |           | not null | 
| bifi_price    | numeric(26,18)           |           | not null | 
| buyback_total | numeric(26,18)           |           |          | generated always as ((bifi_amount * bifi_price)) stored
Indexes:
    "bifi_buyback_pkey" PRIMARY KEY, btree (id)
    "bifi_buyback_idx_txn_timestamp_event_idx" UNIQUE, btree (txn_timestamp DESC, event_idx) INCLUDE (txn_timestamp)
*/

SELECT
  id,
  block_number,
  txn_timestamp,
  event_idx,
  txn_hash,
  bifi_amount,
  bifi_price,
  buyback_total
FROM {{ this }}

