repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast

  #- repo: https://github.com/pre-commit/mirrors-mypy
  #  rev: v1.4.1
  #  hooks:
  #    - id: mypy

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.282
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: local
    hooks:
      - id: mypy-check
        name: mypy-check
        entry: mypy
        language: system
        types: ["python"]

      #- id: pytest-check
      #  name: pytest-check
      #  entry: sh -c 'PYTHONPATH=".:src/" pytest'
      #  language: system
      #  pass_filenames: false
      #  always_run: true
  #- repo: https://github.com/psf/black
  #  rev: 22.10.0
  #  hooks:
  #    - id: black
