version: 2

models:
  - name: product_classic
    description: "Dimension table for classic product (vault) reference data. Provides product/vault metadata for joining with fact tables."
    config:
      contract:
        enforced: true
      meta:
        primary_key: ["chain_id", "vault_address"]
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - chain_id
              - vault_address
      - relationships_multi_key:
          name: relationships_vault_address_token
          arguments:
            to: ref('token')
            from_columns: ["chain_id", "vault_address"]
            to_columns: ["chain_id", "representation_address"]
      - relationships_multi_key:
          name: relationships_underlying_token_representation_address_token
          arguments:
            to: ref('token')
            from_columns:
              ["chain_id", "underlying_token_representation_address"]
            to_columns: ["chain_id", "representation_address"]

    columns:
      - name: chain_id
        description: "Chain ID where the vault exists"
        data_type: Int64
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('chain')
                field: chain_id
      - name: vault_address
        description: "Vault contract address"
        data_type: String
        tests:
          - not_null
      - name: beefy_key
        description: "Beefy-specific vault/product identifier"
        data_type: String
        tests:
          - not_null
      - name: display_name
        description: "Product/vault display name"
        data_type: String
        tests:
          - not_null
      - name: is_active
        description: "Whether the vault is currently active"
        data_type: Bool
        tests:
          - not_null
      - name: latest_strategy_address
        description: "Latest strategy contract address"
        data_type: Nullable(String)
      - name: underlying_token_representation_address
        description: "Underlying token contract address"
        data_type: String
        tests:
          - not_null
