version: 2

models:
  - name: product_reward_pool
    description: "Dimension table for the reward pool product (vault) reference data. Provides product/vault metadata for joining with fact tables."
    config:
      contract:
        enforced: true
      meta:
        primary_key: ["chain_id", "reward_pool_address"]
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - chain_id
              - reward_pool_address
      - relationships_multi_key:
          name: relationships_reward_pool_address_token
          arguments:
            to: ref('token')
            from_columns: ["chain_id", "reward_pool_address"]
            to_columns: ["chain_id", "representation_address"]
      - relationships_multi_key:
          name: relationships_underlying_product_address_product
          arguments:
            to: ref('product')
            from_columns: ["chain_id", "underlying_product_address"]
            to_columns: ["chain_id", "product_address"]
    columns:
      - name: chain_id
        description: "Chain ID where the reward pool exists"
        data_type: Int64
        tests:
          - not_null
      - name: reward_pool_address
        description: "Reward pool contract address"
        data_type: String
        tests:
          - not_null
      - name: beefy_key
        description: "Beefy-specific reward pool/product identifier"
        data_type: String
        tests:
          - not_null
      - name: display_name
        description: "Reward pool display name"
        data_type: String
        tests:
          - not_null
      - name: is_active
        description: "Whether the reward pool is currently active"
        data_type: Bool
        tests:
          - not_null
      - name: underlying_product_address
        description: "Underlying product contract address"
        data_type: String
        tests:
          - not_null
      - name: reward_token_representation_addresses
        description: "Reward token contract addresses"
        data_type: Array(String)
        tests:
          - not_null
