version: 2

models:
  - name: product_clm
    description: "Dimension table for the CLM product (vault) reference data. Provides product/vault metadata for joining with fact tables."
    config:
      contract:
        enforced: true
      meta:
        primary_key: ["chain_id", "vault_address"]
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - chain_id
              - vault_address
      - relationships_multi_key:
          name: relationships_lp_token_representation_address_token
          arguments:
            to: ref('token')
            from_columns: ["chain_id", "lp_token_representation_address"]
            to_columns: ["chain_id", "representation_address"]
      - relationships_array_multi_key:
          name: relationships_underlying_token_representation_addresses_token
          arguments:
            to: ref('token')
            from_chain_column: chain_id
            from_array_column: underlying_token_representation_addresses
            to_chain_column: chain_id
            to_address_column: representation_address

    columns:
      - name: chain_id
        description: "Chain ID where the vault exists"
        data_type: Int64
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('chain')
                field: chain_id
      - name: vault_address
        description: "Vault contract address"
        data_type: String
        tests:
          - not_null
      - name: beefy_key
        description: "Beefy-specific vault/product identifier"
        data_type: String
        tests:
          - not_null
      - name: display_name
        description: "Product/vault display name"
        data_type: String
        tests:
          - not_null
      - name: platform_id
        description: "Platform identifier"
        data_type: String
        tests:
          - relationships:
              arguments:
                to: ref('platform')
                field: platform_id
      - name: is_active
        description: "Whether the vault is currently active"
        data_type: Bool
        tests:
          - not_null
      - name: latest_strategy_address
        description: "Latest strategy contract address"
        data_type: Nullable(String)
      - name: lp_token_representation_address
        description: "LP token contract address emitted by the vault"
        data_type: String
        tests:
          - not_null
      - name: underlying_token_representation_addresses
        description: "Underlying token contract addresses backing the CLM position"
        data_type: Array(String)
        tests:
          - not_null
          - expect_array_length_to_be_between:
              arguments:
                min_value: 2
                max_value: 2
