version: 2

models:
  - name: product_classic
    description: "Dimension table for classic product (vault) reference data. Provides product/vault metadata for joining with fact tables."
    config:
      contract:
        enforced: true
    columns:
      - name: product_id
        description: "Unique identifier for the product (primary key)"
        data_type: String
        tests:
          - not_null
          - unique
      - name: beefy_key
        description: "Beefy-specific vault/product identifier"
        data_type: String
        tests:
          - not_null
      - name: chain_id
        description: "Chain ID where the vault exists"
        data_type: Int64
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('chain')
                field: chain_id
      - name: display_name
        description: "Product/vault display name"
        data_type: String
        tests:
          - not_null
      - name: is_active
        description: "Whether the vault is currently active"
        data_type: Bool
        tests:
          - not_null
      - name: vault_address
        description: "Vault contract address"
        data_type: String
        tests:
          - not_null
      - name: latest_strategy_address
        description: "Latest strategy contract address"
        data_type: Nullable(String)
      - name: underlying_token_address
        description: "Underlying token contract address"
        data_type: String
        tests:
          - not_null
