version: 2

models:
  - name: product_stats
    description: "Timeseries of product stats including TVL, APY, merged breakdowns (APY and LPS), and price. Provides a complete historical view of all product metrics from API snapshots."
    config:
      contract:
        enforced: true
      meta:
        primary_key: ["chain_id", "product_address", "date_hour"]
    tests:
      - relationships_multi_key:
          name: relationships_product_stats_product
          arguments:
            to: ref('product')
            from_columns: ["chain_id", "product_address"]
            to_columns: ["chain_id", "product_address"]
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - chain_id
              - product_address
              - date_hour
    columns:
      - name: chain_id
        description: "Chain ID where the product exists (foreign key to chain.chain_id)"
        data_type: Int64
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('chain')
                field: chain_id
      - name: product_type
        description: "Type of product (classic, clm, or reward_pool)"
        data_type: String
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ["classic", "clm", "reward_pool"]
      - name: beefy_key
        description: "Beefy-specific vault/product identifier (foreign key to product.beefy_key)"
        data_type: String
        tests:
          - not_null
      - name: product_address
        description: "Product contract address (foreign key to product.product_address)"
        data_type: String
        tests:
          - not_null
      - name: display_name
        description: "Product/vault display name"
        data_type: String
        tests:
          - not_null
      - name: is_active
        description: "Whether the vault is currently active"
        data_type: Bool
        tests:
          - not_null
      - name: platform_id
        description: "Platform identifier (foreign key to platform.platform_id)"
        data_type: String
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('platform')
                field: platform_id
      - name: date_hour
        description: "Date when this snapshot was captured"
        data_type: DateTime('UTC')
        tests:
          - not_null
      - name: tvl
        description: "Total value locked in USD"
        data_type: Nullable(Float64)
      - name: apy
        description: "Annual percentage yield"
        data_type: Nullable(Float64)
      - name: compoundings_per_year
        description: "Number of compoundings per year"
        data_type: Nullable(Int64)
      - name: beefy_performance_fee
        description: "Beefy performance fee"
        data_type: Nullable(Float64)
      - name: lp_fee
        description: "LP fee"
        data_type: Nullable(Float64)
      - name: total_apy
        description: "Total APY"
        data_type: Nullable(Float64)
      - name: vault_apr
        description: "Vault APR"
        data_type: Nullable(Float64)
      - name: trading_apr
        description: "Trading APR"
        data_type: Nullable(Float64)
      - name: clm_apr
        description: "CLM APR"
        data_type: Nullable(Float64)
      - name: reward_pool_apr
        description: "Reward pool APR"
        data_type: Nullable(Float64)
      - name: reward_pool_trading_apr
        description: "Reward pool trading APR"
        data_type: Nullable(Float64)
      - name: vault_apy
        description: "Vault APY"
        data_type: Nullable(String)
      - name: liquid_staking_apr
        description: "Liquid staking APR"
        data_type: Nullable(String)
      - name: composable_pool_apr
        description: "Composable pool APR"
        data_type: Nullable(String)
      - name: merkl_apr
        description: "Merkl APR"
        data_type: Nullable(String)
      - name: linea_ignition_apr
        description: "Linea Ignition APR"
        data_type: Nullable(String)
      - name: lp_price
        description: "LP token price"
        data_type: Nullable(Float64)
      - name: tokens
        description: "Tokens information (JSON)"
        data_type: Nullable(String)
      - name: balances
        description: "Balances information (JSON)"
        data_type: Nullable(String)
      - name: total_supply
        description: "Total supply"
        data_type: Nullable(Decimal(38, 9))
      - name: underlying_liquidity
        description: "Underlying liquidity"
        data_type: Nullable(Decimal(38, 9))
      - name: underlying_balances
        description: "Underlying balances (JSON)"
        data_type: Nullable(String)
      - name: price
        description: "Underlying token price in USD"
        data_type: Nullable(Decimal(38, 9))
