version: 2

sources:
  - name: dlt
    description: "Source data from dlt database"
    database: dlt
    schema: dlt
    tables:
      # beefy_api tables
      - name: beefy_api___vaults
        description: "Vault configurations from Beefy API"
      - name: beefy_api___tokens
        description: "Token configurations from Beefy API"
      - name: beefy_api___clm_vaults
        description: "CLM vault configurations from Beefy API"
      - name: beefy_api___cow_vaults
        description: "COW vault configurations from Beefy API"
      - name: beefy_api___gov_vaults
        description: "Governance vault configurations from Beefy API"
      - name: beefy_api___boosts
        description: "Boost configurations from Beefy API"
      # beefy_db tables
      - name: beefy_db___chains
        description: "Chain reference data from Beefy database"
      - name: beefy_db___vault_strategies
        description: "Vault strategy configurations from Beefy database"
      - name: beefy_db___address_metadata
        description: "Address metadata from Beefy database"
      - name: beefy_db___bifi_buyback
        description: "BIFI buyback events from Beefy database"
      - name: beefy_db___feebatch_harvests
        description: "Fee batch harvest events from Beefy database"
      - name: beefy_db___vault_ids
        description: "Vault ID mappings from Beefy database"
      - name: beefy_db___price_oracles
        description: "Price oracle configurations from Beefy database"
      # beefy_api tables
      - name: beefy_api___apy
        description: "APY snapshots from Beefy API"
      - name: beefy_api___treasury
        description: "Treasury snapshots from Beefy API"
      - name: beefy_api___treasury_mm
        description: "Treasury money market snapshots from Beefy API"
      - name: beefy_api___tvl
        description: "TVL snapshots from Beefy API"
      - name: beefy_api___prices
        description: "Price snapshots from Beefy API"
      - name: beefy_api___lps
        description: "LP snapshots from Beefy API"
      - name: beefy_api___lps_breakdown
        description: "LP breakdown snapshots from Beefy API"
      - name: beefy_api___apy_breakdown
        description: "APY breakdown snapshots from Beefy API"
      - name: beefy_api___mootokenprices
        description: "MOO token price snapshots from Beefy API"
      # beefy_db tables
      - name: beefy_db___harvests
        description: "Harvest events from Beefy database"
      - name: beefy_db___prices
        description: "Price data from Beefy database"
      - name: beefy_db___apys
        description: "APY time series from Beefy database"
      - name: beefy_db___tvls
        description: "Vault TVL time series from Beefy database"
      - name: beefy_db___tvl_by_chain
        description: "Chain-level TVL time series from Beefy database"
      # github_files tables
      - name: github_files___beefy_platforms
        description: "Beefy platform configurations from GitHub files"
      - name: github_files___beefy_ui_chains
        description: "Beefy UI chain configurations from GitHub files"
