version: 2

models:
  - name: revenue_buyback_events
    description: "Transform BIFI buyback events into revenue structure. Maps buyback events to a revenue model, where buyback_total represents revenue."
    tests:
      - dbt_utils.expression_is_true:
          arguments:
            expression: "buyback_amount > 0"
          config:
            severity: error
      - dbt_utils.expression_is_true:
          arguments:
            expression: "token_price_usd > 0"
          config:
            severity: error
      - dbt_utils.expression_is_true:
          arguments:
            expression: "buyback_usd > 0"
          config:
            severity: error
    columns:
      - name: id
        description: "Unique identifier for the buyback event"
        tests:
          - not_null
          - unique
      - name: block_number
        description: "Block number where the buyback event occurred"
        tests:
          - not_null
      - name: dim_time
        description: "Timestamp of the buyback event"
        tests:
          - not_null
      - name: event_idx
        description: "Index of the event within the transaction"
      - name: tx_hash
        description: "Transaction hash of the buyback"
        tests:
          - not_null
      - name: token_symbol
        description: "Token symbol (BIFI)"
        tests:
          - not_null
          - accepted_values:
              arguments:
              values: ["BIFI"]
      - name: token_price_usd
        description: "Price of BIFI token at the time of buyback in USD"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: false
      - name: buyback_amount
        description: "Amount of BIFI tokens bought back"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: false
      - name: buyback_usd
        description: "Amount of BIFI tokens bought back in USD"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                inclusive: false
