from enum import StrEnum, unique


@unique
class Chain(StrEnum):
    ARBITRUM = "arbitrum"
    AURORA = "aurora"
    AVAX = "avax"
    BASE = "base"
    BSC = "bsc"
    CANTO = "canto"
    CELO = "celo"
    CRONOS = "cronos"
    EMERALD = "emerald"
    ETHEREUM = "ethereum"
    FANTOM = "fantom"
    FUSE = "fuse"
    GNOSIS = "gnosis"
    HARMONY = "one"
    HECO = "heco"
    KAVA = "kava"
    LINEA = "linea"
    MANTLE = "mantle"
    METIS = "metis"
    MOONBEAM = "moonbeam"
    MOONRIVER = "moonriver"
    OPTIMISM = "optimism"
    POLYGON = "polygon"
    ROLLUX = "rollux"
    SCROLL = "scroll"
    ZKEVM = "zkevm"
    ZKSYNC = "zksync"
