{{
  config(
    materialized='view',
  )
}}

SELECT
  t.assets,
  t.risks,
  t.migration_ids,
  t.point_structure_ids,
  t.zaps,
  cast(t.id as String) as id,
  ifNull(t.name, 'Unknown') as name,
  t.type,
  t.token,
  {{ evm_address('t.token_address') }} as token_address,
  toInt32(t.token_decimals) as token_decimals,
  t.token_provider_id,
  cast({{ evm_address('t.earn_contract_address') }} as String) as earn_contract_address,
  t.earned_token,
  cast({{ evm_address('t.earned_token_address') }} as String) as earned_token_address,
  t.oracle,
  t.oracle_id,
  t.status,
  t.created_at,
  cast(t.platform_id as String) as platform_id,
  t.strategy_type_id,
  t.add_liquidity_url,
  t.remove_liquidity_url,
  {{ normalize_network_beefy_key('t.network') }} as network,
  toBool(t.is_gov_vault) as is_gov_vault,
  {{ evm_address('t.strategy') }} as strategy,
  t.price_per_full_share,
  t.last_harvest,
  t.retire_reason,
  t.retired_at,
  t.buy_token_url,
  t.lending_oracle,
  t.paused_at,
  t.curator_id,
  t.underlying_platform_url,
  t.updated_at,
  t.deposit_fee,
  t.pause_reason,
  toBool(t.refund) as refund,
  {{ evm_address('t.refund_contract_address') }} as refund_contract_address,
  toBool(t.show_warning) as show_warning,
  t.warning,
  toBool(t.earning_points) as earning_points,
  t.pool_together,
  t.retired_reason,
  t.bridged
FROM {{ source('dlt', 'beefy_api___vaults') }} t

