version: 2

models:
  - name: product_stats
    description: "Timeseries of product stats including TVL, APY, merged breakdowns (APY and LPS), and price. Provides a complete historical view of all product metrics from API snapshots."
    config:
      contract:
        enforced: true
      meta:
        primary_key: ["chain_id", "product_address", "date_hour"]
    tests:
      - relationships_multi_key:
          name: relationships_product_stats_product
          arguments:
            to: ref('product')
            from_columns: ["chain_id", "product_address"]
            to_columns: ["chain_id", "product_address"]
      - relationships_array_multi_key:
          name: relationships_product_stats_breakdown_tokens_token
          arguments:
            to: ref('token')
            from_chain_column: chain_id
            from_array_column: breakdown_tokens
            to_chain_column: chain_id
            to_address_column: representation_address
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - chain_id
              - product_address
              - date_hour
    columns:
      - name: chain_id
        description: "Chain ID where the product exists (foreign key to chain.chain_id)"
        data_type: Int64
        codec: ZSTD(3)
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('chain')
                field: chain_id
      - name: product_type
        description: "Type of product"
        data_type: String
        codec: LZ4
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ["classic_vault", "clm_manager", "reward_pool", "classic_boost"]
      - name: beefy_key
        description: "Beefy-specific vault/product identifier (foreign key to product.beefy_key)"
        data_type: String
        codec: LZ4
        tests:
          - not_null
      - name: product_address
        description: "Product contract address (foreign key to product.product_address)"
        data_type: String
        codec: LZ4
        tests:
          - not_null
      - name: display_name
        description: "Product/vault display name"
        data_type: String
        codec: LZ4
        tests:
          - not_null
      - name: is_active
        description: "Whether the vault is currently active"
        data_type: Bool
        codec: LZ4
        tests:
          - not_null
      - name: platform_id
        description: "Platform identifier (foreign key to platform.platform_id)"
        data_type: Nullable(String)
        codec: LZ4
        tests:
          - relationships:
              arguments:
                to: ref('platform')
                field: platform_id
      - name: date_hour
        description: "Date when this snapshot was captured"
        data_type: DateTime('UTC')
        codec: DoubleDelta, LZ4
        tests:
          - not_null
      - name: tvl_usd
        description: "Total value locked in USD"
        data_type: Nullable(Float64)
        codec: ZSTD(3)
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                max_value: 1000000000
                inclusive: true
      - name: apy
        description: "Annual percentage yield"
        data_type: Nullable(Float64)
        codec: ZSTD(3)
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                max_value: 1000000
                inclusive: true
      - name: compoundings_per_year
        description: "Number of compoundings per year"
        data_type: Nullable(Int64)
        codec: ZSTD(3)
      - name: beefy_performance_fee
        description: "Beefy performance fee"
        data_type: Nullable(Float64)
        codec: ZSTD(3)
      - name: lp_fee
        description: "LP fee"
        data_type: Nullable(Float64)
        codec: ZSTD(3)
      - name: total_apy
        description: "Total APY"
        data_type: Nullable(Float64)
        codec: ZSTD(3)
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                max_value: 1000000
                inclusive: true
      - name: vault_apr
        description: "Vault APR"
        data_type: Nullable(Float64)
        codec: ZSTD(3)
      - name: trading_apr
        description: "Trading APR"
        data_type: Nullable(Float64)
        codec: ZSTD(3)
      - name: clm_apr
        description: "CLM APR"
        data_type: Nullable(Float64)
        codec: ZSTD(3)
      - name: reward_pool_apr
        description: "Reward pool APR"
        data_type: Nullable(Float64)
        codec: ZSTD(3)
      - name: reward_pool_trading_apr
        description: "Reward pool trading APR"
        data_type: Nullable(Float64)
        codec: ZSTD(3)
      - name: vault_apy
        description: "Vault APY"
        data_type: Nullable(Float64)
        codec: ZSTD(3)
      - name: liquid_staking_apr
        description: "Liquid staking APR"
        data_type: Nullable(Float64)
        codec: ZSTD(3)
      - name: composable_pool_apr
        description: "Composable pool APR"
        data_type: Nullable(Float64)
        codec: ZSTD(3)
      - name: merkl_apr
        description: "Merkl APR"
        data_type: Nullable(Float64)
        codec: ZSTD(3)
      - name: linea_ignition_apr
        description: "Linea Ignition APR"
        data_type: Nullable(Float64)
        codec: ZSTD(3)
      - name: lp_price
        description: "LP token price"
        data_type: Nullable(Float64)
        codec: ZSTD(3)
      - name: breakdown_tokens
        description: "Tokens Addresses"
        data_type: Array(String)
        codec: LZ4
      - name: breakdown_balances
        description: "Balances information (JSON)"
        data_type: Array(Decimal(76, 20))
        codec: LZ4
      - name: total_supply
        description: "Total supply"
        data_type: Nullable(Decimal(76, 20))
        codec: ZSTD(3)
      - name: underlying_liquidity
        description: "Underlying liquidity"
        data_type: Nullable(Decimal(76, 20))
        codec: ZSTD(3)
      - name: underlying_balances
        description: "Underlying balances"
        data_type: Array(Decimal(76, 20))
        codec: LZ4
      - name: underlying_price
        description: "Underlying token price in USD"
        data_type: Nullable(Decimal(76, 20))
        codec: ZSTD(3)
      - name: underlying_amount_compounded
        description: "Underlying amount compounded"
        data_type: Nullable(Decimal(76, 20))
        codec: ZSTD(3)
      - name: underlying_token_price_usd
        description: "Underlying token price in USD"
        data_type: Nullable(Decimal(76, 20))
        codec: ZSTD(3)
      - name: underlying_amount_compounded_usd
        description: "Underlying amount compounded in USD"
        data_type: Nullable(Decimal(76, 20))
        codec: ZSTD(3)