{{
  config(
    materialized='view',
  )
}}

SELECT
  assets,
  risks,
  migration_ids,
  point_structure_ids,
  zaps,
  assumeNotNull(id) as id,
  assumeNotNull(name) as name,
  type,
  token,
  assumeNotNull({{ evm_address('token_address') }}) as token_address,
  assumeNotNull(toInt32(token_decimals)) as token_decimals,
  token_provider_id,
  assumeNotNull({{ evm_address('earn_contract_address') }}) as earn_contract_address,
  earned_token,
  assumeNotNull({{ evm_address('earned_token_address') }}) as earned_token_address,
  oracle,
  oracle_id,
  status,
  created_at,
  platform_id,
  strategy_type_id,
  add_liquidity_url,
  remove_liquidity_url,
  {{ normalize_network_beefy_key('network') }} as network,
  toBool(is_gov_vault) as is_gov_vault,
  {{ evm_address('strategy') }} as strategy,
  price_per_full_share,
  last_harvest,
  retire_reason,
  retired_at,
  buy_token_url,
  lending_oracle,
  paused_at,
  curator_id,
  underlying_platform_url,
  updated_at,
  deposit_fee,
  pause_reason,
  toBool(refund) as refund,
  {{ evm_address('refund_contract_address') }} as refund_contract_address,
  toBool(show_warning) as show_warning,
  warning,
  toBool(earning_points) as earning_points,
  pool_together,
  retired_reason,
  bridged
FROM {{ source('dlt', 'beefy_api_configs___vaults') }}
WHERE token_address IS NOT NULL

